services:
  foosball-csharp-api:
    image: foosball-api:csharp
    restart: on-failure
    build:
      context: .
      dockerfile: Foosball.CSharp.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__FOOSBALLDB: 'host=${FOOSBALL_DB_HOSTNAME};port=5432;database=${FOOSBALL_DB_HOSTNAME};password=${FOOSBALL_DB_POSTGRES_PASSWORD};username=${FOOSBALL_DB_POSTGRES_USER}'
    ports:
      - 8080:80

  foosball-csharp-db:
    image: postgres:alpine
    container_name: ${FOOSBALL_DB_HOSTNAME}
    restart: on-failure
    environment:
      POSTGRES_USER: '${FOOSBALL_DB_POSTGRES_USER}'
      POSTGRES_PASSWORD: '${FOOSBALL_DB_POSTGRES_PASSWORD}'
    ports:
      - 5432:80
